server:
  port: 10000


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      enabled: true
      routes:
        - id: book-service-id
          uri: lb://publisher-book
          predicates:
          - Path=/book/**
        - id: author-search-service-id
          uri: lb://publisher-author-search
          predicates :
          - Path=/author/search/**
        - id: author-maintenance-service-id
          uri: lb://publisher-author-maintenance
          predicates:
          - Path=/author/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG